### PR TITLE
DRIVERS: add roboteq and velodyne drivers

### PR DESCRIPTION
**Pull request by kev-the-dev**
* Both the velodyne and roboteq driver are no longer on the kinetic apt repository (despite them working on kinetic). So these are both added as a submodule

### CODE REVIEW

**Comment by RustyBamboo** [comment]
Oh cool, we should probably hold off on merging this until we confirm that everything works IRL.

**Review by RustyBamboo — APPROVED** [review]

**Comment by kev-the-dev** [comment]
Note: will not build until docker image is rebuilt with new install script dependencies (serial)

**Comment by Grymessa** [comment]
Reran the checks after building new image. Passed the cmake so it should be good to go though there may be some formatting errors to fix.

**Comment by kev-the-dev** [comment]
@Grymestone so the docker image on the CI server is updated?

**Comment by Grymessa** [comment]
@ironmig Yep, rebuilt as of yesterday night.

**Comment by kev-the-dev** [comment]
Yay it builds now! Good work. Next step: NaviGator CI

**Comment by kev-the-dev** [comment]
Both drivers tested

**Pull request merged**
