### PR TITLE
BUG: Fix eigen include on some systems

### PR DESCRIPTION
**Pull request by kingkevlar**
Debian 8.7

### CODE REVIEW

**Review by mattlangford — COMMENTED** [review]
I've never seen this issue before, what is the root cause?

**Comment by sentree** [comment]
Let's try to keep this discussion on uf-mil/SubjuGator#225 since the pull requests are so similar.

**Review by kev-the-dev — APPROVED** [review]
Good. Should prevent some edge case build errors.

**Review by DSsoto — APPROVED** [review]
Approve. The issue was the capitalization of eigen. Apparently on Debian there are multiple eigen_include_dirs variables and the capitalization affected which include paths were added.

**Pull request merged**
