### PR TITLE
REPO: Namespace changes to prepare for sub8 integration

### PR DESCRIPTION
**Pull request by kev-the-dev**
* rename nav namespaces in vision lib to mil_vision
* rename mil::tools namesapce to mil_tools (agreed during meeting on 4/8
* move some non-msg things in mil_msgs to mil_tools
* tested to build with common pruned sub8 repo uf-mil/SubjuGator#216

### CODE REVIEW

**Comment by sentree** [comment]
This built on the CI and passed all unit tests except the ros_alarms test that always fails.
-- Your friendly temporary CI guy

**Comment by sentree** [comment]
These changes did not build. The following error was reported:

    error: mil_msgs/Float64Stamped.h: No such file or directory

 -- Your friendly temporary CI guy

**Comment by whispercoros** [comment]
This built on the CI and passed all unit tests except the ros_alarms test that always fails.
-- Your friendly temporary CI guy

**Comment by sentree** [comment]
This built on the CI and passed all unit tests except the ros_alarms test that always fails.
-- Your friendly temporary CI guy

**Pull request merged**
