### PR TITLE
SUBMODULE: added submodule for LMS1xx driver

### PR DESCRIPTION
**Pull request by thefata**

### CODE REVIEW

**Comment by kev-the-dev** [comment]
Looks like the build is failing due to formatting checks in the submodule. It's other people's code, so we shouldn't format check it. [Apply this patch](https://git-scm.com/docs/git-apply) to skip the driver in format checks

```
diff --git a/Jenkinsfile b/Jenkinsfile
index b28112c..a432e0b 100755
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@ -36,7 +36,7 @@ dockerNode(image: 'uf-mil:navigator') {
 		sh '''
 			source /opt/ros/kinetic/setup.bash > /dev/null 2>&1
 			wget -O ~/.clang-format https://raw.githubusercontent.com/uf-mil/installer/master/.clang-format
-			for FILE in $(find -path ./deprecated -prune -o -path ./simulation/vmrc -prune -o -regex ".*/.*\\.\\(c\\|cc\\|cpp\\|h\\|hpp\\)$"); do
+			for FILE in $(find -path ./deprecated -prune -o -path ./simulation/vmrc -prune -o -path ./drivers/LMS1xx -prune -o -regex ".*/.*\\.\\(c\\|cc\\|cpp\\|h\\|hpp\\)$"); do
 				if [ ! -z "$(clang-format-3.8 -style=file -output-replacements-xml $FILE | grep '<replacement ')" ]; then
 					FILES+=( "$FILE" )
 				fi
```

**Comment by thefata** [comment]
I have applied the patch, however there are two Python scripts whose formatting is still being checked.

**Comment by kev-the-dev** [comment]
```
diff --git a/scripts/bash_aliases.sh b/scripts/bash_aliases.sh
index bd0dfbd..63edf68 100755
--- a/scripts/bash_aliases.sh
+++ b/scripts/bash_aliases.sh
@@ -82,7 +82,7 @@ alias nhold="rosrun ros_alarms raise station-hold"
 alias nviz="rviz -d \$CATKIN_DIR/src/NaviGator/navigator.rviz"
 
 # Development
-alias navfmt="python2.7 -m flake8 --ignore E731 --max-line-length=120 \$(rosrun mil_tools list_python_files \$CATKIN_DIR/src/NaviGator __init__.py deprecated/ gnc/navigator_path_planner/lqRRT .cfg simulation/vmrc)"
+alias navfmt="python2.7 -m flake8 --ignore E731 --max-line-length=120 \$(rosrun mil_tools list_python_files \$CATKIN_DIR/src/NaviGator __init__.py deprecated/ gnc/navigator_path_planner/lqRRT .cfg simulation/vmrc drivers/LMS1xx)"
 alias navtest="(cd \$CATKIN_DIR; rosrun mil_tools catkin_tests_directory.py src/NaviGator)"
 
 # Work around for bagging to SSD and copying to HDD when possible
```

**Comment by kev-the-dev** [comment]
Looks like you messed up somewhere with git, checkout your diff on github

**Comment by kev-the-dev** [comment]
closing in favor of #154

**Comment by thefata** [comment]
Probably a good move, my git history was messed up and the primary aim of the pull request was to add the submodule.

**Pull request closed without merging**
